name: CI Pipeline

on:
  push:
    branches:
      - main  # Run the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Run the pipeline on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use the Python version that matches your local setup

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pwd
        ls
        pip install -r requirements.txt  # Install the required packages listed in requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Discover and run tests in the 'tests' directory
